### ISSUE TITLE
Location of the code repositories for the data models.

### ISSUE THREAD

**Issue by romulogoncalves** [phenology/hsr-phenological-modelling#3]
To understand the data models to be used in this project, the location of code repositories, description of old set-ups, etc. would be very useful to understand the requirements for the project.

**Comment by foost** [comment]
I have added Emma as she knows the details about the code repositories. We will discuss this on March 29.

**Comment by romulogoncalves** [comment]
Let's add a more detail description on which code repository, technical reports, or how-to for:

- "Last year we organized a DataCamp in cooperation with the database group of our university and CBS, where we experimented with Spark to produce similar green-wave maps for the Netherlands"

- Where can we find code and report related with: "The maps shown in this website could only be produced thanks to a Google Faculty Award that allowed us to implement the SI-x models in Google’s Earth Engine."

- " A demonstration of this research can be seen on our Green-wave website". Where is the web-site data hosted and how was the data obtained/processed?

**Comment by romulogoncalves** [comment]
All code is shared through by granting access to private repositories which was already done.
