### ISSUE TITLE
Ingest MODIS data

### ISSUE THREAD

**Issue by rzuritamilla** [phenology/hsr-phenological-modelling#7]
MCD12Q2. Let's try pyMODIS. Bounding box CONUS
Other RS data (AVHRR, etc) with longer time series are in the making...

**Comment by rzuritamilla** [comment]
Before I forget, we should mask out water, and other less relevant classes (snow, urban) before doing our SVD analysis. We will create this mask based on [MCD12Q1](https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table/mcd12q1)

**Comment by romulogoncalves** [comment]
The data was loaded with success and documentation was added in how to load it. 
https://github.com/phenology/hsr-phenological-modelling/tree/master/modis
