### ISSUE TITLE
Ingest SI-x other resolutions

### ISSUE THREAD

**Issue by rzuritamilla** [phenology/hsr-phenological-modelling#8]
GRIDMET 4km; BEST 100km

**Comment by romulogoncalves** [comment]
@rzuritamilla and @EIzquierdo do we really need to load the 100KM resolution?
At the moment we have the 4KM resolution and I think that's enough. Lower resolutions are simply manageable without Spark.

If yes, we have already loaded Gridmet and SOST 4km, therefore, the issue can be closed.

**Comment by romulogoncalves** [comment]
The 100Km resolution will not be used in the project. Its size is too small to require the use of Spark.
