### ISSUE TITLE
Matrix operations

### ISSUE THREAD

**Issue by rzuritamilla** [phenology/hsr-phenological-modelling#9]
cell operations (Z-Score) and region operations ("reducers")

**Comment by romulogoncalves** [comment]
@rzuritamilla 

More information is required for this issue.
Matrix multiplication is achieved in Spark using BlockMatrices.

If not more information is provided, the issue will be closed.

**Comment by romulogoncalves** [comment]
Matrix operations are handled by Spark distributed Matrices. 
One example is matrix multiplication for large matrices, it was achieved using IndexedMatrix as outer matrix and Matrix as inner matrix.  The test was done with SOST (1km) x LeafFinal (4km) and then run SVD on the result.
